[2024-10-15T02:26:00.232+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-15T02:26:00.412+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_dag_iron.insert_data_inc scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-15T02:26:00.468+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_dag_iron.insert_data_inc scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-15T02:26:00.697+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-15T02:26:07.196+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-10-14 00:00:00+00:00
[2024-10-15T02:26:07.213+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=355) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-15T02:26:07.217+0000] {standard_task_runner.py:64} INFO - Started process 382 to run task
[2024-10-15T02:26:07.219+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'query_dag_iron', 'insert_data_inc', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '1168', '--raw', '--subdir', 'DAGS_FOLDER/iron.py', '--cfg-path', '/tmp/tmpn5jp5s6l']
[2024-10-15T02:26:07.224+0000] {standard_task_runner.py:91} INFO - Job 1168: Subtask insert_data_inc
[2024-10-15T02:26:08.919+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-15T02:26:08.997+0000] {task_command.py:426} INFO - Running <TaskInstance: query_dag_iron.insert_data_inc scheduled__2024-10-14T00:00:00+00:00 [running]> on host 92783cd12528
[2024-10-15T02:26:09.001+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:356 DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
[2024-10-15T02:26:09.982+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/secrets_masker.py:84 DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
[2024-10-15T02:26:10.715+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='query_dag_iron' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-14T00:00:00+00:00'
[2024-10-15T02:26:10.951+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-15T02:26:10.994+0000] {sql.py:282} INFO - Executing: insert into hive.iron.customer select *  from sqlserver.dbo.soul
[2024-10-15T02:26:11.028+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-10-15T02:26:11.054+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-10-15T02:26:11.063+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-10-15T02:26:11.070+0000] {sql.py:495} INFO - Running statement: insert into hive.iron.customer select *  from sqlserver.dbo.soul, parameters: None
[2024-10-15T02:26:11.099+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-15T02:26:11.099+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoQueryError: TrinoQueryError(type=INTERNAL_ERROR, name=SERVER_STARTING_UP, message="Trino server is still initializing", query_id=20241015_022611_00010_a6fby)
[2024-10-15T02:26:11.119+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=query_dag_iron, task_id=insert_data_inc, run_id=scheduled__2024-10-14T00:00:00+00:00, execution_date=20241014T000000, start_date=20241015T022600, end_date=20241015T022611
[2024-10-15T02:26:11.472+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1168 for task insert_data_inc (TrinoQueryError(type=INTERNAL_ERROR, name=SERVER_STARTING_UP, message="Trino server is still initializing", query_id=20241015_022611_00010_a6fby); 382)
[2024-10-15T02:26:11.525+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-15T02:26:11.785+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
