[2024-11-01T03:06:41.969+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-01T03:06:42.013+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test.insert_data_inc manual__2024-11-01T03:06:38.426290+00:00 [queued]>
[2024-11-01T03:06:42.025+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test.insert_data_inc manual__2024-11-01T03:06:38.426290+00:00 [queued]>
[2024-11-01T03:06:42.029+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-01T03:06:42.047+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-11-01 03:06:38.426290+00:00
[2024-11-01T03:06:42.055+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=96361) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-01T03:06:42.058+0000] {standard_task_runner.py:64} INFO - Started process 96374 to run task
[2024-11-01T03:06:42.057+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'insert_data_inc', 'manual__2024-11-01T03:06:38.426290+00:00', '--job-id', '2348', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpn2n3ilco']
[2024-11-01T03:06:42.062+0000] {standard_task_runner.py:91} INFO - Job 2348: Subtask insert_data_inc
[2024-11-01T03:06:42.091+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-01T03:06:42.130+0000] {task_command.py:426} INFO - Running <TaskInstance: test.insert_data_inc manual__2024-11-01T03:06:38.426290+00:00 [running]> on host 92783cd12528
[2024-11-01T03:06:42.210+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/secrets_masker.py:84 DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
[2024-11-01T03:06:42.256+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T03:06:38.426290+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-01T03:06:38.426290+00:00'
[2024-11-01T03:06:42.257+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-01T03:06:42.276+0000] {sql.py:282} INFO - Executing: insert into hive.test.nganhangso select * from sqlserver.dbo.nganhangso where date_format(d_date_time, '%Y%m%d') = '20240627'
[2024-11-01T03:06:42.294+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-11-01T03:06:42.304+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-11-01T03:06:42.312+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-11-01T03:06:42.316+0000] {sql.py:495} INFO - Running statement: insert into hive.test.nganhangso select * from sqlserver.dbo.nganhangso where date_format(d_date_time, '%Y%m%d') = '20240627', parameters: None
[2024-11-01T03:06:51.826+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-01T03:06:51.827+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 581, in _process_error
    raise exceptions.TrinoExternalError(error, query_id)
trino.exceptions.TrinoExternalError: TrinoExternalError(type=EXTERNAL, name=HIVE_METASTORE_ERROR, message="Failed connecting to Hive metastore: [hive-metastore:9083]", query_id=20241031_121048_00090_mawje)
[2024-11-01T03:06:51.841+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=test, task_id=insert_data_inc, run_id=manual__2024-11-01T03:06:38.426290+00:00, execution_date=20241101T030638, start_date=20241101T030642, end_date=20241101T030651
[2024-11-01T03:06:51.864+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2348 for task insert_data_inc (TrinoExternalError(type=EXTERNAL, name=HIVE_METASTORE_ERROR, message="Failed connecting to Hive metastore: [hive-metastore:9083]", query_id=20241031_121048_00090_mawje); 96374)
[2024-11-01T03:06:51.901+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-01T03:06:51.911+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class TrinoOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
[2024-11-01T03:06:51.929+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-01T03:06:51.932+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
