[2024-08-26T00:26:48.640+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-26T00:26:48.702+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trino_query_dag.insert_data_inc scheduled__2024-08-23T00:00:00+00:00 [queued]>
[2024-08-26T00:26:48.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trino_query_dag.insert_data_inc scheduled__2024-08-23T00:00:00+00:00 [queued]>
[2024-08-26T00:26:48.878+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-26T00:26:49.041+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-08-23 00:00:00+00:00
[2024-08-26T00:26:49.084+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'trino_query_dag', 'insert_data_inc', 'scheduled__2024-08-23T00:00:00+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmphg1tursu']
[2024-08-26T00:26:49.128+0000] {standard_task_runner.py:91} INFO - Job 176: Subtask insert_data_inc
[2024-08-26T00:26:49.127+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2608) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-26T00:26:49.146+0000] {standard_task_runner.py:64} INFO - Started process 2615 to run task
[2024-08-26T00:26:49.315+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-26T00:26:49.420+0000] {task_command.py:426} INFO - Running <TaskInstance: trino_query_dag.insert_data_inc scheduled__2024-08-23T00:00:00+00:00 [running]> on host b476143e3d64
[2024-08-26T00:26:50.361+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trino_query_dag' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-08-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-23T00:00:00+00:00'
[2024-08-26T00:26:50.410+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-26T00:26:50.480+0000] {sql.py:282} INFO - Executing: insert into hive.test.nganhangso select * from sqlserver.dbo.nganhangso where date_format(d_date_time, '%Y%m%d') = '20240627'
[2024-08-26T00:26:50.577+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-26T00:26:50.629+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-26T00:26:50.682+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-26T00:26:50.710+0000] {sql.py:495} INFO - Running statement: insert into hive.test.nganhangso select * from sqlserver.dbo.nganhangso where date_format(d_date_time, '%Y%m%d') = '20240627', parameters: None
[2024-08-26T00:27:35.307+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-26T00:27:35.308+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 581, in _process_error
    raise exceptions.TrinoExternalError(error, query_id)
trino.exceptions.TrinoExternalError: TrinoExternalError(type=EXTERNAL, name=HIVE_METASTORE_ERROR, message="hive-metastore:9083: java.net.SocketTimeoutException: Read timed out", query_id=20240823_101835_00000_qxrrb)
[2024-08-26T00:27:36.657+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=trino_query_dag, task_id=insert_data_inc, run_id=scheduled__2024-08-23T00:00:00+00:00, execution_date=20240823T000000, start_date=20240826T002648, end_date=20240826T002736
[2024-08-26T00:27:44.066+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 176 for task insert_data_inc (TrinoExternalError(type=EXTERNAL, name=HIVE_METASTORE_ERROR, message="hive-metastore:9083: java.net.SocketTimeoutException: Read timed out", query_id=20240823_101835_00000_qxrrb); 2615)
[2024-08-26T00:27:44.196+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-26T00:27:44.253+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class TrinoOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
[2024-08-26T00:27:44.321+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-26T00:27:50.718+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
