[2024-08-27T02:05:03.209+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-27T02:05:03.246+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T01:00:00+00:00 [queued]>
[2024-08-27T02:05:03.257+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T01:00:00+00:00 [queued]>
[2024-08-27T02:05:03.258+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-27T02:05:03.276+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-08-27 01:00:00+00:00
[2024-08-27T02:05:03.289+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=19509) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-27T02:05:03.290+0000] {standard_task_runner.py:64} INFO - Started process 19510 to run task
[2024-08-27T02:05:03.289+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'trino_query_dag_ivory', 'insert_data_inc', 'scheduled__2024-08-27T01:00:00+00:00', '--job-id', '390', '--raw', '--subdir', 'DAGS_FOLDER/ivory.py', '--cfg-path', '/tmp/tmpk9amitkx']
[2024-08-27T02:05:03.292+0000] {standard_task_runner.py:91} INFO - Job 390: Subtask insert_data_inc
[2024-08-27T02:05:03.309+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-27T02:05:03.355+0000] {task_command.py:426} INFO - Running <TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T01:00:00+00:00 [running]> on host b476143e3d64
[2024-08-27T02:05:03.449+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trino_query_dag_ivory' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-08-27T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-27T01:00:00+00:00'
[2024-08-27T02:05:03.450+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-27T02:05:03.466+0000] {sql.py:282} INFO - Executing: insert into hive.ivory.customer select *  from sqlserver.dbo.customer
[2024-08-27T02:05:03.489+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-27T02:05:03.501+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-27T02:05:03.510+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-27T02:05:03.515+0000] {sql.py:495} INFO - Running statement: insert into hive.ivory.customer select *  from sqlserver.dbo.customer, parameters: None
[2024-08-27T02:05:03.773+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-27T02:05:03.779+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="Insert query has mismatched column types: Table: [integer, date, varchar(50), varchar(100), varchar(50), varchar(10), varchar(50), varchar(20), varchar(50)], Query: [double, timestamp(3), varchar(255), varchar(255), varchar(255), double, varchar(255), double, varchar(255)]", query_id=20240826_112504_00134_kfczv)
[2024-08-27T02:05:03.793+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=trino_query_dag_ivory, task_id=insert_data_inc, run_id=scheduled__2024-08-27T01:00:00+00:00, execution_date=20240827T010000, start_date=20240827T020503, end_date=20240827T020503
[2024-08-27T02:05:03.808+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 390 for task insert_data_inc (TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="Insert query has mismatched column types: Table: [integer, date, varchar(50), varchar(100), varchar(50), varchar(10), varchar(50), varchar(20), varchar(50)], Query: [double, timestamp(3), varchar(255), varchar(255), varchar(255), double, varchar(255), double, varchar(255)]", query_id=20240826_112504_00134_kfczv); 19510)
[2024-08-27T02:05:03.827+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-27T02:05:03.840+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-27T02:14:51.883+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-27T02:14:51.924+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T01:00:00+00:00 [queued]>
[2024-08-27T02:14:51.934+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T01:00:00+00:00 [queued]>
[2024-08-27T02:14:51.935+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-27T02:14:51.949+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-08-27 01:00:00+00:00
[2024-08-27T02:14:51.956+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=19824) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-27T02:14:51.957+0000] {standard_task_runner.py:64} INFO - Started process 19825 to run task
[2024-08-27T02:14:51.956+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'trino_query_dag_ivory', 'insert_data_inc', 'scheduled__2024-08-27T01:00:00+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/ivory.py', '--cfg-path', '/tmp/tmpvn9c_a0j']
[2024-08-27T02:14:51.958+0000] {standard_task_runner.py:91} INFO - Job 400: Subtask insert_data_inc
[2024-08-27T02:14:51.974+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-27T02:14:52.014+0000] {task_command.py:426} INFO - Running <TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T01:00:00+00:00 [running]> on host b476143e3d64
[2024-08-27T02:14:52.106+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trino_query_dag_ivory' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-08-27T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-27T01:00:00+00:00'
[2024-08-27T02:14:52.107+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-27T02:14:52.122+0000] {sql.py:282} INFO - Executing: insert into hive.ivory.customer select *  from sqlserver.dbo.customer
[2024-08-27T02:14:52.138+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-27T02:14:52.147+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-27T02:14:52.156+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-27T02:14:52.161+0000] {sql.py:495} INFO - Running statement: insert into hive.ivory.customer select *  from sqlserver.dbo.customer, parameters: None
[2024-08-27T02:14:52.455+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-27T02:14:52.457+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="Insert query has mismatched column types: Table: [integer, date, varchar(50), varchar(100), varchar(50), varchar(10), varchar(50), varchar(20), varchar(50)], Query: [double, timestamp(3), varchar(255), varchar(255), varchar(255), double, varchar(255), double, varchar(255)]", query_id=20240826_113452_00139_kfczv)
[2024-08-27T02:14:52.473+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=trino_query_dag_ivory, task_id=insert_data_inc, run_id=scheduled__2024-08-27T01:00:00+00:00, execution_date=20240827T010000, start_date=20240827T021451, end_date=20240827T021452
[2024-08-27T02:14:52.491+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 400 for task insert_data_inc (TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="Insert query has mismatched column types: Table: [integer, date, varchar(50), varchar(100), varchar(50), varchar(10), varchar(50), varchar(20), varchar(50)], Query: [double, timestamp(3), varchar(255), varchar(255), varchar(255), double, varchar(255), double, varchar(255)]", query_id=20240826_113452_00139_kfczv); 19825)
[2024-08-27T02:14:52.533+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-27T02:14:52.549+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
